### ISSUE TITLE
Namensgebung

### ISSUE THREAD

**Issue by StrayDog2205** [MeisterTR/ioBroker.worx#10]
Wäre es möglich im Adapter einen Namen für den Mäher zu vergeben und diesen anstelle der SerienNr. in den Objektbaum (oberordner) zu schreiben? 

Speziell für Skripte welche man weitergeben möchte wäre das sicher interessant.

**Comment by MeisterTR** [comment]
Möglich wäre es aber Aufwand zu Nutzen nicht tragbar. Da eine Zeile am Anfang vom Script wo die Seriennummer definiert kein Mehraufwand bedeutet. Und der Name vom Mäher auch mit in den object Namen steht.
