### ISSUE TITLE
How to install it

### ISSUE THREAD

**Issue by gekomax** [MeisterTR/ioBroker.worx#11]
Hi, thanks for your development.

I'm really noob at this.

How can I install it on Hass runnning on docker?

Thanks

**Comment by MeisterTR** [comment]
You only need to select the adapter ind your Admin and install it.

gekomax <notifications@github.com> schrieb am Mo., 24. Juni 2019, 11:00:

**Comment by gekomax** [comment]
Sorry, I'm sure to understand what you are referring to.

Is there some sort of "apt-get install" for that you say?

Please excuse my being a noob 

Thanks

**Comment by MeisterTR** [comment]
This Programm is only a plugin for a smarthome system called iobroker. So
you habe to install iobroker first.

gekomax <notifications@github.com> schrieb am Mo., 24. Juni 2019, 13:13:
