### ISSUE TITLE
Conecting to worx did not work

### ISSUE THREAD

**Issue by Fiiti** [MeisterTR/ioBroker.worx#12]
Hi,
I can sign in to https://account.worxlandroid.com with my credentials.
But in iobroker it does not work.
Any suggestions? 

Here the downloaded settings anonymised
`{
  "_id": "system.adapter.worx.0",
  "common": {
    "name": "worx",
    "version": "0.3.1",
    "title": "Worx Landroid Cloud",
    "authors": [
      "MeisterTR <meistertr.smarthome@gmail.com>"
    ],
    "keywords": [
      "ioBroker",
      "mower",
      "Landroid",
      "Worx",
      "Smart Home",
      "home automation"
    ],
    "license": "MIT",
    "platform": "Javascript/Node.js",
    "main": "main.js",
    "icon": "worx.png",
    "enabled": true,
    "extIcon": "https://raw.githubusercontent.com/MeisterTR/ioBroker.worx/master/admin/worx.png",
    "readme": "https://github.com/MeisterTR/ioBroker.worx/blob/master/README.md",
    "loglevel": "info",
    "mode": "daemon",
    "type": "garden",
    "compact": true,
    "materialize": true,
    "installedVersion": "0.3.1",
    "host": "nubroker"
  },
  "native": {
    "mail": "xxxx@online.de",
    "password": "yyyy",
    "edgeCutDelay": "5000"
  }
}`

regards
Fi

**Comment by MeisterTR** [comment]
Debug log?

**Comment by Fiiti** [comment]
The short one:
`host.nubroker	2019-06-30 13:40:30.717	info	Restart adapter system.adapter.worx.0 because enabled
host.nubroker	2019-06-30 13:40:30.717	error	instance system.adapter.worx.0 terminated with code 1 ()
host.nubroker	2019-06-30 13:40:30.715	error	Caught by controller[0]: /opt/iobroker/node_modules/iobroker.worx/main.js:65
host.nubroker	2019-06-30 13:40:30.546	info	instance system.adapter.worx.0 started with pid 7087
host.nubroker	2019-06-30 13:40:00.531	info	Restart adapter system.adapter.worx.0 because enabled
host.nubroker	2019-06-30 13:40:00.531	error	instance system.adapter.worx.0 terminated with code 1 ()
host.nubroker	2019-06-30 13:40:00.529	error	Caught by controller[0]: /opt/iobroker/node_modules/iobroker.worx/main.js:65
host.nubroker	2019-06-30 13:40:00.360	info	instance system.adapter.worx.0 started with pid 7081`

With more details:
`host.nubroker	2019-06-30 13:41:31.113	info	Restart adapter system.adapter.worx.0 because enabled
host.nubroker	2019-06-30 13:41:31.113	error	instance system.adapter.worx.0 terminated with code 1 ()
host.nubroker	2019-06-30 13:41:31.113	error	Caught by controller[0]: at startup (bootstrap_node.js:160:9)
host.nubroker	2019-06-30 13:41:31.113	error	Caught by controller[0]: at run (bootstrap_node.js:394:7)
host.nubroker	2019-06-30 13:41:31.112	error	Caught by controller[0]: at Module.runMain (module.js:611:10)
host.nubroker	2019-06-30 13:41:31.112	error	Caught by controller[0]: at Function.Module._load (module.js:445:3)
host.nubroker	2019-06-30 13:41:31.112	error	Caught by controller[0]: at tryModuleLoad (module.js:453:12)
host.nubroker	2019-06-30 13:41:31.112	error	Caught by controller[0]: at Module.load (module.js:494:32)
host.nubroker	2019-06-30 13:41:31.112	error	Caught by controller[0]: at Object.Module._extensions..js (module.js:586:10)
host.nubroker	2019-06-30 13:41:31.112	error	Caught by controller[0]: at Module._compile (module.js:549:28)
host.nubroker	2019-06-30 13:41:31.112	error	Caught by controller[0]: at Object.runInThisContext (vm.js:97:10)
host.nubroker	2019-06-30 13:41:31.112	error	Caught by controller[0]: at createScript (vm.js:56:10)
host.nubroker	2019-06-30 13:41:31.112	error	Caught by controller[0]: SyntaxError: Unexpected token ...
host.nubroker	2019-06-30 13:41:31.112	error	Caught by controller[0]: ^^^
host.nubroker	2019-06-30 13:41:31.111	error	Caught by controller[0]: ...options,
host.nubroker	2019-06-30 13:41:31.111	error	Caught by controller[0]: /opt/iobroker/node_modules/iobroker.worx/main.js:65
host.nubroker	2019-06-30 13:41:30.941	info	instance system.adapter.worx.0 started with pid 7107
host.nubroker	2019-06-30 13:41:00.922	info	Restart adapter system.adapter.worx.0 because enabled
host.nubroker	2019-06-30 13:41:00.922	error	instance system.adapter.worx.0 terminated with code 1 ()
host.nubroker	2019-06-30 13:41:00.922	error	Caught by controller[0]: at startup (bootstrap_node.js:160:9)
host.nubroker	2019-06-30 13:41:00.922	error	Caught by controller[0]: at run (bootstrap_node.js:394:7)
host.nubroker	2019-06-30 13:41:00.922	error	Caught by controller[0]: at Module.runMain (module.js:611:10)
host.nubroker	2019-06-30 13:41:00.922	error	Caught by controller[0]: at Function.Module._load (module.js:445:3)
host.nubroker	2019-06-30 13:41:00.921	error	Caught by controller[0]: at tryModuleLoad (module.js:453:12)
host.nubroker	2019-06-30 13:41:00.921	error	Caught by controller[0]: at Module.load (module.js:494:32)
host.nubroker	2019-06-30 13:41:00.921	error	Caught by controller[0]: at Object.Module._extensions..js (module.js:586:10)
host.nubroker	2019-06-30 13:41:00.921	error	Caught by controller[0]: at Module._compile (module.js:549:28)
host.nubroker	2019-06-30 13:41:00.921	error	Caught by controller[0]: at Object.runInThisContext (vm.js:97:10)
host.nubroker	2019-06-30 13:41:00.921	error	Caught by controller[0]: at createScript (vm.js:56:10)
host.nubroker	2019-06-30 13:41:00.921	error	Caught by controller[0]: SyntaxError: Unexpected token ...
host.nubroker	2019-06-30 13:41:00.921	error	Caught by controller[0]: ^^^
host.nubroker	2019-06-30 13:41:00.921	error	Caught by controller[0]: ...options,
host.nubroker	2019-06-30 13:41:00.920	error	Caught by controller[0]: /opt/iobroker/node_modules/iobroker.worx/main.js:65
host.nubroker	2019-06-30 13:41:00.741	info	instance system.adapter.worx.0 started with pid 7100
host.nubroker	2019-06-30 13:40:30.717	info	Restart adapter system.adapter.worx.0 because enabled
host.nubroker	2019-06-30 13:40:30.717	error	instance system.adapter.worx.0 terminated with code 1 ()
host.nubroker	2019-06-30 13:40:30.717	error	Caught by controller[0]: at startup (bootstrap_node.js:160:9)
host.nubroker	2019-06-30 13:40:30.716	error	Caught by controller[0]: at run (bootstrap_node.js:394:7)
host.nubroker	2019-06-30 13:40:30.716	error	Caught by controller[0]: at Module.runMain (module.js:611:10)
host.nubroker	2019-06-30 13:40:30.716	error	Caught by controller[0]: at Function.Module._load (module.js:445:3)
host.nubroker	2019-06-30 13:40:30.716	error	Caught by controller[0]: at tryModuleLoad (module.js:453:12)
host.nubroker	2019-06-30 13:40:30.716	error	Caught by controller[0]: at Module.load (module.js:494:32)
host.nubroker	2019-06-30 13:40:30.716	error	Caught by controller[0]: at Object.Module._extensions..js (module.js:586:10)
host.nubroker	2019-06-30 13:40:30.716	error	Caught by controller[0]: at Module._compile (module.js:549:28)
host.nubroker	2019-06-30 13:40:30.716	error	Caught by controller[0]: at Object.runInThisContext (vm.js:97:10)
host.nubroker	2019-06-30 13:40:30.716	error	Caught by controller[0]: at createScript (vm.js:56:10)
host.nubroker	2019-06-30 13:40:30.716	error	Caught by controller[0]: SyntaxError: Unexpected token ...
host.nubroker	2019-06-30 13:40:30.715	error	Caught by controller[0]: ^^^
host.nubroker	2019-06-30 13:40:30.715	error	Caught by controller[0]: ...options,
host.nubroker	2019-06-30 13:40:30.715	error	Caught by controller[0]: /opt/iobroker/node_modules/iobroker.worx/main.js:65
host.nubroker	2019-06-30 13:40:30.546	info	instance system.adapter.worx.0 started with pid 7087
host.nubroker	2019-06-30 13:40:00.531	info	Restart adapter system.adapter.worx.0 because enabled`

**Comment by Fiiti** [comment]
Er kommt also mit der Zeile 65 "...options" nicht klar
>constructor(options) {
        super({
            ...options,
            name: 'worx',
});

**Comment by MeisterTR** [comment]
Node update, 6 wird nicht mehr unterstützt
