### ISSUE TITLE
difference btw actualAreaIndicator and actualArea

### ISSUE THREAD

**Issue by gekomax** [MeisterTR/ioBroker.worx#15]
I've got worx adapter working on iobroker.
 This is a question more than a issue:
What is the difference between actualAreaIndicator and actualArea?
According what I'm seeing:

 actual area = the number of the defined area where the landroid is working

but, what about actualAreaIndicator? Now it gives to me a value of 5 that I don't uderstand.

Can you give some tips?
Thanlk a lot

**Comment by MeisterTR** [comment]
actualAreaIndicator is the value that is select from the startseqens. eg: 

startsequenz: 0,1,2,3,4,0,0,0,0,0
actualAreaIndicator : 2

so the area will be 2
