### ISSUE TITLE
iobroker.worx - mqtt goto home

### ISSUE THREAD

**Issue by rogerbl** [MeisterTR/ioBroker.worx#18]
Hi! I got the iobroker.worx adapter working now with my S300 mower and Mqtt adapter.
I figured out how to send start(iobroker/worx/0/2019xxxxxxxxxxxxxxxCD/mower/state=true)
 and pause(iobroker/worx/0/2019xxxxxxxxxxxxCD/mower/pause=1) commands but what is the goto home command? iobroker/worx/0/2019xxxxxxxxxxxxxxxxxxxxxCD/mower/????
**********************
Found it ! :-) It simply state=false

**Comment by MeisterTR** [comment]
home(iobroker/worx/0/2019xxxxxxxxxxxxxxxCD/mower/state=false)
