### ISSUE TITLE
I get blocked from Worx

### ISSUE THREAD

**Issue by rogerbl** [MeisterTR/ioBroker.worx#21]
Hello!
    I wonder if there is a way to slow down the worx adapter? Currently it is updating every 3 second and Worx has blocked me several times due to this. They say I spam them with requests.

Here is part of my log:
worx.0 2019-08-23 22:28:44.099 warn Connection blocked from Worx, please try again in 24h
worx.0 2019-08-23 22:28:41.861 info starting. Version 0.4.0 in C:/WINDOWS/system32/node_modules/iobroker.worx, node: v10.16.0
host.DESKTOP-BF47MV5 2019-08-23 22:28:40.184 info instance system.adapter.worx.0 started with pid 49688
host.DESKTOP-BF47MV5 2019-08-23 22:28:10.177 info Restart adapter system.adapter.worx.0 because enabled
host.DESKTOP-BF47MV5 2019-08-23 22:28:10.177 error instance system.adapter.worx.0 terminated with code 0 (OK)
Caught 2019-08-23 22:28:10.177 error by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
Caught 2019-08-23 22:28:10.177 error by controller[0]: at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
Caught 2019-08-23 22:28:10.177 error by controller[0]: at emitErrorNT (internal/streams/destroy.js:91:8)
Caught 2019-08-23 22:28:10.177 error by controller[0]: at TLSSocket.emit (events.js:203:15)
Caught 2019-08-23 22:28:10.177 error by controller[0]: at TLSSocket.handleTLSerrors (C:\WINDOWS\system32\node_modules\iobroker.worx\node_modules\mqtt\lib\connect\tls.js:26:18)
Caught 2019-08-23 22:28:10.177 error by controller[0]: at MqttClient.emit (events.js:198:13)
Caught 2019-08-23 22:28:10.177 error by controller[0]: at MqttClient.<anonymous> (C:\WINDOWS\system32\node_modules\iobroker.worx\lib\api.js:259:13)
Caught 2019-08-23 22:28:10.176 error by controller[0]: ReferenceError: reject is not defined
worx.0 2019-08-23 22:28:10.153 info cleaned everything up...
worx.0 2019-08-23 22:28:10.153 error at process._tickCallback (internal/process/next_tick.js:63:19)
worx.0 2019-08-23 22:28:10.153 error at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
worx.0 2019-08-23 22:28:10.153 error at emitErrorNT (internal/streams/destroy.js:91:8)
worx.0 2019-08-23 22:28:10.153 error at TLSSocket.emit (events.js:203:15)
worx.0 2019-08-23 22:28:10.153 error at TLSSocket.handleTLSerrors (C:\WINDOWS\system32\node_modules\iobroker.worx\node_modules\mqtt\lib\connect\tls.js:26:18)
worx.0 2019-08-23 22:28:10.153 error at MqttClient.emit (events.js:198:13)
worx.0 2019-08-23 22:28:10.153 error at MqttClient.<anonymous> (C:\WINDOWS\system32\node_modules\iobroker.worx\lib\api.js:259:13)
worx.0 2019-08-23 22:28:10.153 error ReferenceError: reject is not defined
worx.0 2019-08-23 22:28:10.152 error uncaught exception: reject is not defined

**Comment by MeisterTR** [comment]
please stop adapter for 24 hours. install the version from git, activate debug log and post the log again

**Comment by rogerbl** [comment]
Thanks!
Is the 0.4.0 the last version of the adapter?

Regards Roger

Fra: MeisterTR <notifications@github.com>
Sendt: lørdag 24. august 2019 20.03
Til: MeisterTR/ioBroker.worx <ioBroker.worx@noreply.github.com>
Kopi: rogerbl <rogerbl@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [MeisterTR/ioBroker.worx] I get blocked from Worx (#21)


please stop adapter for 24 hours. install the version from git, activate debug log and post the log again

**Comment by MeisterTR** [comment]
Yes but you have to install the version from git because I have changed logging and fixed an error

**Comment by rogerbl** [comment]
Ok, thanks!

Regards Roger

Fra: MeisterTR <notifications@github.com>
Sendt: lørdag 24. august 2019 20.54
Til: MeisterTR/ioBroker.worx <ioBroker.worx@noreply.github.com>
Kopi: rogerbl <rogerbl@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [MeisterTR/ioBroker.worx] I get blocked from Worx (#21)


Yes but you have to install the version from git because I have changed logging and fixed an error

**Comment by rogerbl** [comment]
Perfect!
Now it works fine! What a good job you have done!
I have been connected since I updated the adapter last night!
Thanks a lot! 😊

Regards Roger

Fra: MeisterTR <notifications@github.com>
Sendt: lørdag 24. august 2019 20.54
Til: MeisterTR/ioBroker.worx <ioBroker.worx@noreply.github.com>
Kopi: rogerbl <rogerbl@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [MeisterTR/ioBroker.worx] I get blocked from Worx (#21)


Yes but you have to install the version from git because I have changed logging and fixed an error

**Comment by rogerbl** [comment]
Hi again!
I was again blocked …

Regards Roger

Fra: MeisterTR <notifications@github.com>
Sendt: lørdag 24. august 2019 20.03
Til: MeisterTR/ioBroker.worx <ioBroker.worx@noreply.github.com>
Kopi: rogerbl <rogerbl@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [MeisterTR/ioBroker.worx] I get blocked from Worx (#21)


please stop adapter for 24 hours. install the version from git, activate debug log and post the log again

**Comment by rogerbl** [comment]
Hi again!
I don’t see any error messages connected to your adapter, but worx blocked me anyway.
Will try to disable other adapters to see if they are influencing the worx adapter.
Specially the mqtt client adapter which I use.
I’ll let you know what I find out.

Regards Roger

Fra: MeisterTR <notifications@github.com>
Sendt: lørdag 24. august 2019 20.54
Til: MeisterTR/ioBroker.worx <ioBroker.worx@noreply.github.com>
Kopi: rogerbl <rogerbl@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [MeisterTR/ioBroker.worx] I get blocked from Worx (#21)


Yes but you have to install the version from git because I have changed logging and fixed an error

**Comment by rogerbl** [comment]
Hi!
After I moved the iobroker installation to a raspberry pi, worx don’t block
me anymore.
The other iobroker was on a win 10 pc.
Thanks for your good work! 😊

Regards Roger

Fra: MeisterTR <notifications@github.com>
Sendt: lørdag 24. august 2019 20.54
Til: MeisterTR/ioBroker.worx <ioBroker.worx@noreply.github.com>
Kopi: rogerbl <rogerbl@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [MeisterTR/ioBroker.worx] I get blocked from Worx (#21)


Yes but you have to install the version from git because I have changed logging and fixed an error

**Comment by rogerbl** [comment]
Hi!
when the edgecut command is issued on a mower without edgecut option, the adapter spam worx server and it blocks the connection for 24h.
My mower is a S300 without edgecut option.
I tested it on both my iobroker installations.
So win10 was not the problem. 😊 Good to know!

Regards Roger

Fra: MeisterTR <notifications@github.com>
Sendt: lørdag 24. august 2019 20.03
Til: MeisterTR/ioBroker.worx <ioBroker.worx@noreply.github.com>
Kopi: rogerbl <rogerbl@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [MeisterTR/ioBroker.worx] I get blocked from Worx (#21)


please stop adapter for 24 hours. install the version from git, activate debug log and post the log again

**Comment by MeisterTR** [comment]
interesting is a debug log. normaly you shouln,t blocked from worx.  So i thing something is wrong

**Comment by rogerbl** [comment]
Yes, I understand , but there is not much to see in the degbug log.


Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Fra: MeisterTR <notifications@github.com>
Sendt: Thursday, August 29, 2019 7:42:33 PM
Til: MeisterTR/ioBroker.worx <ioBroker.worx@noreply.github.com>
Kopi: rogerbl <rogerbl@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [MeisterTR/ioBroker.worx] I get blocked from Worx (#21)


interesting is a debug log. normaly you shouln,t blocked from worx. So i thing something is wrong
