### ISSUE TITLE
Adapter lässt sicht nicht starten

### ISSUE THREAD

**Issue by LJSven** [MeisterTR/ioBroker.worx#25]
Ich habe ein Backup eingespielt - seitdem lässt sich der Adapter (0.4.0) nicht mehr starten. Ich bekomme folgende Meldung:

> host.tinkerboardmaster | 2019-10-14 12:12:01.726 | error | instance system.adapter.worx.0 terminated with code 0 (OK)
> -- | -- | -- | --
> Caught | 2019-10-14 12:12:01.726 | error | by controller[0]:     at Timer.processTimers (timers.js:223:10)
> Caught | 2019-10-14 12:12:01.726 | error | by controller[0]:     at listOnTimeout (timers.js:263:5)
> Caught | 2019-10-14 12:12:01.726 | error | by controller[0]:     at tryOnTimeout (timers.js:300:5)
> Caught | 2019-10-14 12:12:01.726 | error | by controller[0]:     at ontimeout (timers.js:436:11)
> Caught | 2019-10-14 12:12:01.726 | error | by controller[0]:     at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.worx/main.js:107:30)
> Caught | 2019-10-14 12:12:01.725 | error | by controller[0]:     at Worx.setStates (/opt/iobroker/node_modules/iobroker.worx/main.js:174:32)
> Caught | 2019-10-14 12:12:01.725 | error | by controller[0]: TypeError: Cannot read property 'st' of undefined
> worx.0
>

**Comment by MeisterTR** [comment]
sollte erledigt sein
