### ISSUE TITLE
Edge cut

### ISSUE THREAD

**Issue by StrayDog2205** [MeisterTR/ioBroker.worx#8]
Das aktivieren des "Edge cut" Datenpunktes sorgt zwar dafür, das er den Rand abfährt, dabei bleibt das Mähwerk allerdings ausgeschaltet.

Gibt es da einen "Trick" bzw. irgendwas, was man dort in der Schalt-reihenfolge beachten muss?

**Comment by MeisterTR** [comment]
Welche fw hast du installiert? Es muss mindestens die 3.45 sein. Ansonsten geht es nicht. Falls das der Fall ist, brauche ich einen Debug log um genaueres zu sagen. Mfg

**Comment by StrayDog2205** [comment]
Firmware habe ich 2.82.
Die wird mir auch als aktuellste angezeigt.

Im durchgang eben hatte ich den Zeitversatz auf 10.000ms stehen.
Er hat allerdins erst deutlich später angefangen den Rand zu mähen.

Debug:
`2019-06-11 20:27:00.877 - info: worx.0 id_____ worx.0.SerialNr.mower.edgecut Mower SerialNr_____edgecut______{"domain":null,"_events":{},"_eventsCount":1,"_maxListeners":100,"serial":"SerialNr","online":true,"raw":{"id":356164,"product_id":49,"user_id":198197,"serial_number":"SerialNr","mac_address":"MACAdr","name":"M","purchased_at":"2019-05-26 00:00:00","warranty_expires_at":"Date 00:00:00","setup_location":{"latitude":50.2371917,"longitude":6.7556444},"locked":true,"created_at":"2019-03-15 07:55:05","updated_at":"2019-06-11 17:36:33","firmware_version":2.82,"registered_at":"2019-05-28 00:00:00","firmware_auto_upgrade":false,"distance_covered":8378,"mower_work_time":640,"blade_work_time":605,"battery_charge_cycles":13,"messages_in":174,"messages_out":2473,"push_notifications":true,"city_id":2890335,"push_notifications_level":"notice","lawn_size":70,"raw_messages_in":315,"raw_messages_out":2473,"test":0,"iot_registered":true,"warranty_registered":true,"pin_code":"XxXx","time_zone_id":135,"activated":true,"dealer_id":null,"activated_at":null,"sim_id":null,"app_settings":null,"lawn_perimeter":null,"hubspot_deal_id":801491149,"needs_hubspot_sync":1,"accessories":null,"message_logging_expires_at":null,"is_owner_changed":false,"auto_schedule":0,"auto_schedule_settings":null,"city":{"id":2890335,"country_id":276,"name":"Kirchweiler","latitude":50.23333,"longitude":6.75,"created_at":"2018-02-15 22:22:43","updated_at":"2018-02-15 22:22:43"},"time_zone":"Europe/Berlin","online":true,"mqtt_topics":{"command_in":"PRM100/MACAdr/commandIn","command_out":"PRM100/MACAdr/commandOut"}},"edgeCut":false,"mqtt_command_in":"PRM100/MACAdr/commandIn","mqtt_command_out":"PRM100/MACAdr/commandOut","mqttC":{"options":{"protocol":"mqtts","slashes":true,"auth":null,"host":"a1optpg91s0ydf-ats.iot.eu-west-1.amazonaws.com","port":8883,"hostname":"a1optpg91s0ydf-ats.iot.eu-west-1.amazonaws.com","hash":null,"search":"","query":{},"pathname":null,"href":"mqtts://a1optpg91s0ydf-ats.iot.eu-west-1.amazonaws.com","pfx":{"type":"Buffer","data":[48,130,9,149,2,1,3,48,130,9,95,6,9,42,134,72,134,247,13,1,7,1,160,130,9,80,4,130,9,76,48,130,9,72,48,130,3,255,6,9,42,134,72,134,247,13,1,7,6,160,130,3,240,48,130,3,236,2,1,0,48,130,3,229,6,9,42,134,72,134,247,13,1,7,1,48,28,6,10,42,134,72,134,247,13,1,12,1,6,48,14,4,8,109,135,155,97,160,101,180,73,2,2,8,0,128,130,3,184,3,74,90,107,59,140,115,150,96,33,88,109,203,147,72,166,208,132,8,85,182,174,248,13,142,228,234,111,243,24,199,153,241,17,121,21,101,192,226,226,254,231,228,70,105,172,91,102,226,63,192,52,200,150,139,169,170,74,76,229,33,166,45,171,147,145,104,222,182,41,161,199,161,214,65,124,147,107,204,249,63,72,213,244,228,29,33,222,164,238,108,95,177,50,85,86,65,87,224,143,238,157,141,42,178,229,100,175,248,86,243,186,62,24,83,158,169,151,232,244,42,42,156,151,217,187,115,60,90,149,234,55,36,179,52,134,214,113,186,213,160,61,184,148,185,43,205,115,28,39,86,181,63,191,206,166,69,26,22,15,116,98,220,243,63,83,16,5,231,87,145,91,71,206,68,97,189,55,219,3,110,176,202,151,209,83,37,207,154,48,161,130,169,102,127,71,42,243,149,57,6,57,47,201,235,42,59,26,133,149,95,7,91,166,238,229,84,123,46,237,98,79,2,253,68,72,179,49,208,142,49,231,142,203,202,154,81,241,76,81,76,194,52,209,73,10,197,111,152,50,147,241,253,17,131,226,33,119,131,36,105,60,95,91,65,144,41,31,14,209,151,95,28,104,119,42,99,73,202,29,147,154,127,77,27,120,246,209,136,31,103,89,228,10,102,130,44,253,144,38,173,135,12,55,56,88,142,103,194,188,230,155,86,224,81,206,47,197,54,60,84,16,79,157,72,168,144,90,139,96,59,214,251,29,70,239,116,114,150,155,136,74,62,142,2,47,101,11,20,119,75,211,205,204,97,242,100,247,35,16,152,232,162,189,213,177,188,26,59,76,139,87,162,108,133,79,217,219,161,10,72,158,109,252,237,192,200,1,57,20,93,210,188,215,101,253,136,11,221,116,187,8,56,198,198,102,143,61,104,100,152,153,87,45,136,11,167,60,236,90,184,89,211,16,3,136,147,11,210,243,224,66,130,165,7,37,139,124,142,222,209,218,254,29,253,180,167,181,225,47,112,147,166,155,21,124,34,34,244,183,108,107,143,0,21,58,15,37,162,65,148,54,58,215,35,215,225,141,78,131,28,215,251,138,22,231,46,177,186,17,185,195,244,97,96,159,74,81,76,3,41,181,171,113,163,254,47,137,242,83,106,28,5,53,243,92,235,227,159,37,75,49,56,104,236,55,137,45,188,134,76,48,92,56,47,66,59,174,185,182,244,89,84,171,143,13,164,238,80,224,107,215,125,77,4,225,30,61,52,111,237,207,79,216,8,95,155,169,85,144,9,111,82,54,235,223,40,240,26,161,64,113,187,118,154,1,39,136,45,113,110,175,130,1,251,181,65,207,38,160,245,247,155,125,200,142,33,10,242,71,231,230,143,105,174,42,132,194,157,168,159,58,156,89,11,95,202,196,78,188,107,92,106,229,200,240,67,220,114,39,199,85,17,114,22,172,62,15,70,200,254,232,204,250,222,123,16,247,17,67,151,59,236,196,210,60,33,181,175,95,148,101,204,174,178,217,26,186,92,100,185,132,59,31,38,141,86,144,211,73,210,169,239,233,16,12,182,15,100,13,95,224,36,186,164,1,93,203,127,172,89,214,93,208,159,216,30,45,83,187,49,25,199,126,37,165,25,135,155,210,250,8,174,40,212,163,145,247,240,49,184,49,184,144,216,67,250,228,235,164,147,102,160,35,167,80,70,100,46,251,216,195,125,46,213,238,206,255,95,161,1,20,33,94,1,223,33,215,156,144,65,169,128,183,36,87,123,59,157,254,117,193,0,189,150,58,46,20,16,120,107,31,41,92,151,254,68,122,203,178,36,48,55,158,136,107,204,8,121,1,201,179,120,171,52,12,184,52,135,227,59,158,149,86,189,104,25,8,0,46,98,149,6,56,89,128,142,234,90,42,161,136,52,59,225,183,247,219,41,200,246,77,100,1,114,227,83,52,212,228,225,186,247,226,4,140,165,60,83,235,31,242,192,160,177,135,195,241,28,111,82,215,69,216,23,230,127,220,202,254,253,232,136,183,22,79,164,27,208,171,92,115,123,113,53,155,165,75,15,238,43,18,227,89,46,84,206,186,63,194,118,124,28,117,118,68,181,149,36,17,161,123,0,167,11,221,4,126,144,201,22,157,48,130,5,65,6,9,42,134,72,134,247,13,1,7,1,160,130,5,50,4,130,5,46,48,130,5,42,48,130,5,38,6,11,42,134,72,134,247,13,1,12,10,1,2,160,130,4,238,48,130,4,234,48,28,6,10,42,134,72,134,247,13,1,12,1,3,48,14,4,8,168,50,32,79,77,0,162,215,2,2,8,0,4,130,4,200,86,15,217,145,24,174,140,64,210,118,213,92,166,91,198,240,94,102,189,176,238,23,92,190,91,36,219,223,217,86,196,92,19,198,140,133,81,180,228,200,39,255,197,244,34,23,248,161,125,86,13,163,129,100,127,115,139,21,242,213,213,109,142,31,165,203,234,254,13,49,203,183,22,23,48,76,90,239,162,87,253,95,223,218,153,194,170,219,96,225,100,50,45,154,154,156,224,59,226,233,8,25,4,150,82,216,203,233,5,45,167,25,94,38,65,2,99,231,142,173,84,106,53,15,0,22,27,103,179,217,220,57,98,9,199,9,207,247,44,128,27,191,14,233,104,240,217,61,161,23,156,41,167,252,43,71,107,183,190,22,51,63,226,0,224,86,112,55,82,232,145,28,41,144,51,250,169,50,248,10,215,0,50,219,216,165,17,154,231,128,109,88,13,135,98,190,90,103,154,125,219,116,172,39,11,133,5,249,1,133,193,69,251,117,115,53,197,157,218,12,16,251,240,211,179,162,49,50,87,231,237,166,152,128,106,199,79,104,111,149,196,253,140,73,114,191,27,66,125,33,3,129,182,101,209,243,152,136,76,56,46,215,219,148,12,254,192,248,1,164,224,249,110,107,81,164,18,150,171,151,12,166,190,120,100,27,82,216,29,3,41,65,207,57,26,209,200,70,25,132,78,226,138,37,162,26,53,0,193,95,247,61,226,153,117,44,9,21,250,141,225,116,18,58,163,220,105,56,142,109,81,25,205,88,251,156,145,50,234,72,223,78,105,254,91,14,199,106,125,20,237,182,42,143,186,173,61,81,153,245,136,26,75,154,116,128,136,123,194,76,163,9,20,252,23,193,84,99,243,129,204,148,182,93,240,135,87,77,215,226,88,179,104,226,143,13,223,110,187,234,93,151,220,185,142,66,27,87,130,73,78,170,168,45,122,83,111,163,111,235,168,204,151,49,107,80,187,180,77,158,71,154,58,63,197,136,197,75,161,199,252,231,79,44,226,35,81,132,184,228,118,163,215,165,247,110,77,247,182,9,132,216,221,166,97,119,117,141,46,230,190,214,213,83,212,133,195,128,235,171,52,189,134,89,199,234,86,234,11,251,130,122,225,228,69,0,193,111,246,190,199,228,59,123,35,50,72,196,227,238,191,27,44,178,251,133,159,205,85,160,30,186,113,213,10,189,178,34,164,93,8,119,89,187,139,52,143,129,41,34,215,241,35,244,141,97,54,57,25,140,97,16,169,178,63,73,89,28,73,218,228,176,212,71,26,226,61,98,206,162,191,119,226,139,211,50,3,231,188,234,51,245,108,25,117,87,92,237,76,22,14,186,46,195,190,45,160,97,80,55,50,12,120,172,31,80,218,137,226,228,224,51,199,69,58,221,232,207,204,71,45,73,162,148,82,78,134,219,203,90,251,10,68,173,51,185,129,44,119,69,24,153,21,225,252,179,220,104,89,209,205,80,206,89,203,158,43,44,50,212,194,158,130,55,222,26,246,7,100,175,131,239,50,82,58,174,19,105,44,9,249,169,116,116,42,181,165,60,106,148,209,21,7,161,239,113,145,108,111,55,243,207,16,115,35,237,252,64,210,166,241,7,61,72,104,101,93,79,9,226,13,50,68,138,140,160,97,134,27,43,202,20,252,94,39,155,95,42,18,205,249,114,226,230,81,3,237,102,165,175,181,163,206,158,143,185,172,55,38,51,171,197,67,82,46,31,144,254,197,213,67,73,96,201,115,88,42,28,224,163,51,106,29,71,8,127,43,237,208,13,21,84,131,224,54,87,145,2,88,245,191,50,104,94,86,181,42,20,203,235,203,228,4,4,46,231,213,114,23,94,128,135,212,133,116,104,204,142,240,28,132,252,15,67,134,226,114,139,150,247,244,147,182,149,96,19,82,21,61,202,189,229,22,200,162,247,212,169,243,218,62,170,177,207,127,104,240,148,211,81,25,54,221,108,217,22,182,98,138,173,210,3,92,172,43,144,216,141,148,73,46,2,237,18,123,0,37,11,215,160,206,52,126,88,252,43,106,100,118,97,1,69,142,49,233,29,202,203,38,17,117,234,55,218,20,30,238,72,94,70,214,217,70,221,48,200,161,67,144,148,24,32,96,114,4,122,113,172,156,162,107,134,54,51,64,132,197,48,167,99,53,114,247,247,100,106,200,209,37,57,112,46,86,50,116,21,221,139,103,61,107,152,211,0,116,72,17,111,125,10,19,225,208,189,216,210,242,127,92,37,60,161,192,197,132,245,22,196,156,35,0,3,66,179,42,94,131,248,153,230,8,90,112,248,19,12,80,87,48,201,197,177,57,135,97,49,97,164,18,207,255,169,78,237,140,149,120,43,128,11,53,104,93,222,90,87,240,48,79,101,70,174,157,220,244,40,17,108,255,216,157,144,32,92,95,192,130,124,58,166,107,87,130,98,51,163,243,226,133,133,224,238,157,35,147,91,143,51,94,90,244,100,211,165,197,252,137,169,182,225,60,48,255,242,64,137,210,160,53,131,250,104,234,165,12,80,1,124,247,190,37,200,186,1,102,82,243,144,25,165,195,49,226,166,246,55,158,64,162,41,207,134,86,2,74,32,27,217,20,195,197,29,249,216,174,165,211,250,112,255,112,245,155,250,246,247,122,137,239,114,149,71,114,0,161,120,219,208,171,203,244,35,231,126,206,197,169,253,146,8,154,129,167,25,5,163,147,137,47,237,197,153,70,165,171,119,25,83,154,105,94,180,81,30,49,37,48,35,6,9,42,134,72,134,247,13,1,9,21,49,22,4,20,51,135,160,139,11,150,35,20,116,30,224,217,148,234,143,114,78,250,232,131,48,45,48,33,48,9,6,5,43,14,3,2,26,5,0,4,20,187,238,87,0,89,207,40,71,69,160,66,8,223,180,214,128,171,77,52,54,4,8,109,80,143,211,85,47,138,100]},"clientId":"android-2de62d80-8c76-11e9-9305-05c4fe34fe9f","defaultProtocol":"mqtts","keepalive":60,"reschedulePings":true,"protocolId":"MQTT","protocolVersion":4,"reconnectPeriod":1000,"connectTimeout":30000,"clean":true,"resubscribe":true,"rejectUnauthorized":true},"outgoingStore":{"options":{"clean":true},"_inflights":{}},"incomingStore":{"options":{"clean":true},"_inflights":{}},"queueQoSZero":true,"_resubscribeTopics":{"PRM100/MACAdr/commandOut":{"qos":0}},"messageIdToTopic":{"1487":["PRM100/MACAdr/commandOut"]},"pingTimer":{"_args":[],"_interval":{"_called":false,"_idleTimeout":60000,"_idlePrev":{"_idleNext":"~mqttC~pingTimer~_interval","_idlePrev":{"_called":true,"_idleTimeout":60000,"_idlePrev":"~mqttC~pingTimer~_interval","_idleNext":"~mqttC~pingTimer~_interval~_idlePrev","_idleStart":126461,"_repeat":60000,"_destroyed":false},"_timer":{"_list":"~mqttC~pingTimer~_interval~_idlePrev"},"_unrefed":false,"msecs":60000,"nextTick":false},"_idleNext":"~mqttC~pingTimer~_interval~_idlePrev~_idlePrev","_idleStart":132842,"_timerArgs":["~mqttC~pingTimer~_args"],"_repeat":60000,"_destroyed":false}},"connected":true,"disconnecting":false,"queue":[],"connackTimer":{"0":null,"_called":false,"_idleTimeout":-1,"_idlePrev":null,"_idleNext":null,"_idleStart":6453,"_onTimeout":null,"_repeat":null,"_destroyed":false},"reconnectTimer":null,"_storeProcessing":false,"_packetIdsDuringStoreProcessing":{},"nextId":1490,"outgoing":{},"_firstConnection":false,"_events":{"close":[null,null,null],"connect":[null,null]},"_eventsCount":4,"domain":null,"_maxListeners":100,"stream":{"_tlsOptions":{"pipe":false,"secureContext":{"context":{},"singleUse":true},"isServer":false,"requestCert":true,"rejectUnauthorized":true},"_secureEstablished":true,"_securePending":false,"_newSessionPending":false,"_controlReleased":true,"_SNICallback":null,"servername":false,"alpnProtocol":false,"authorized":true,"authorizationError":null,"encrypted":true,"_events":{"close":[null,null],"end":[null,null]},"_eventsCount":7,"connecting":false,"_hadError":false,"_handle":{"_parent":{"reading":true,"owner":"~mqttC~stream","onread":null,"onconnection":null,"writeQueueSize":0},"_secureContext":"~mqttC~stream~_tlsOptions~secureContext","reading":true,"owner":"~mqttC~stream","writeQueueSize":0},"_parent":null,"_host":"a1optpg91s0ydf-ats.iot.eu-west-1.amazonaws.com","_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":{"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":false,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"domain":null,"_events":{},"_eventsCount":5,"_maxListeners":100},"pipesCount":1,"flowing":true,"ended":false,"endEmitted":false,"reading":true,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"destroyed":false,"defaultEncoding":"utf8","awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":null,"_maxListeners":1000,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":false,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":false,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":{"next":null,"entry":null},"entry":null}},"writable":true,"allowHalfOpen":false,"_bytesDispatched":176,"_sockname":null,"_pendingData":null,"_pendingEncoding":"","_server":null,"ssl":"~mqttC~stream~_handle","_requestCert":true,"_rejectUnauthorized":true},"reconnecting":false,"pingResp":true},"weatherdata":{"coord":{"lon":6.75,"lat":50.23},"weather":[{"id":500,"main":"Rain","description":"light rain","icon":"10d"}],"base":"stations","main":{"temp":16.75,"pressure":1012,"humidity":67,"temp_min":13.89,"temp_max":20.56},"visibility":10000,"wind":{"speed":1.5,"deg":30},"rain":{"3h":0.562},"clouds":{"all":98},"dt":1560277313,"sys":{"type":1,"id":1244,"message":0.0067,"country":"DE","sunrise":1560223378,"sunset":1560282142},"timezone":7200,"id":2890335,"name":"Kirchweiler","cod":200},"message":{"cfg":{"id":0,"lg":"it","tm":"20:25:15","dt":"11/06/2019","sc":{"m":1,"p":0,"d":[["00:00",0,0],["00:00",0,1],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,1],["00:00",0,0]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"SerialNr"},"dat":{"mac":"MACAdr","fw":2.82,"bt":{"t":18.3,"v":19.41,"p":100,"nr":14,"c":0,"m":0},"dmp":[0.4,-4.6,358.6],"st":{"b":653,"d":9165,"wt":689,"bl":47},"ls":1,"le":0,"lz":0,"rsi":-68,"lk":1,"act":1,"conn":"wifi"}}}
2019-06-11 20:27:02.475 - debug: worx.0 DATA: {"cfg":{"id":1,"lg":"it","tm":"20:27:00","dt":"11/06/2019","sc":{"m":1,"p":0,"d":[["00:00",0,0],["00:00",0,1],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,1],["00:00",0,0]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"SerialNr"},"dat":{"mac":"MACAdr","fw":2.82,"bt":{"t":18.3,"v":19.41,"p":100,"nr":14,"c":0,"m":0},"dmp":[0.6,-4.8,358.6],"st":{"b":653,"d":9165,"wt":689,"bl":47},"ls":1,"le":0,"lz":0,"rsi":-71,"lk":1,"act":1,"conn":"wifi"}}
2019-06-11 20:27:02.476 - debug: worx.0 Test Status: 1
2019-06-11 20:27:02.480 - debug: worx.0 Edgecut Start section :1
2019-06-11 20:27:12.264 - debug: worx.0 DATA: {"cfg":{"id":0,"lg":"it","tm":"20:27:10","dt":"11/06/2019","sc":{"m":1,"p":0,"d":[["00:00",0,0],["00:00",0,1],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,1],["00:00",0,0]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"SerialNr"},"dat":{"mac":"MACAdr","fw":2.82,"bt":{"t":18.3,"v":19.37,"p":100,"nr":14,"c":0,"m":0},"dmp":[-3.3,-8.4,347.6],"st":{"b":653,"d":9165,"wt":689,"bl":47},"ls":3,"le":0,"lz":0,"rsi":-71,"lk":1,"act":1,"conn":"wifi"}}
2019-06-11 20:27:12.265 - debug: worx.0 Test Status: 3
2019-06-11 20:27:12.268 - debug: worx.0 Edgecut Start section :3
2019-06-11 20:27:14.825 - debug: worx.0 DATA: {"cfg":{"id":0,"lg":"it","tm":"20:27:13","dt":"11/06/2019","sc":{"m":1,"p":0,"d":[["00:00",0,0],["00:00",0,1],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,1],["00:00",0,0]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"SerialNr"},"dat":{"mac":"MACAdr","fw":2.82,"bt":{"t":18.3,"v":19.32,"p":100,"nr":14,"c":0,"m":0},"dmp":[3.8,-3.6,23.6],"st":{"b":653,"d":9166,"wt":689,"bl":47},"ls":31,"le":0,"lz":0,"rsi":-71,"lk":1,"act":1,"conn":"wifi"}}
2019-06-11 20:27:14.829 - debug: worx.0 Test Status: 31
2019-06-11 20:27:24.832 - debug: worx.0 Edcut send cmd:2
2019-06-11 20:27:38.711 - debug: worx.0 DATA: {"cfg":{"id":0,"lg":"it","tm":"20:27:36","dt":"11/06/2019","sc":{"m":1,"p":0,"d":[["00:00",0,0],["00:00",0,1],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,1],["00:00",0,0]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"SerialNr"},"dat":{"mac":"MACAdr","fw":2.82,"bt":{"t":18.3,"v":19.29,"p":100,"nr":14,"c":0,"m":0},"dmp":[3.6,4.7,151.4],"st":{"b":653,"d":9168,"wt":689,"bl":47},"ls":31,"le":0,"lz":0,"rsi":-71,"lk":1,"act":1,"conn":"wifi"}}
2019-06-11 20:27:38.712 - debug: worx.0 Test Status: 31
2019-06-11 20:27:50.225 - debug: worx.0 DATA: {"cfg":{"id":0,"lg":"it","tm":"20:27:48","dt":"11/06/2019","sc":{"m":1,"p":0,"d":[["00:00",0,0],["00:00",0,1],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,1],["00:00",0,0]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"SerialNr"},"dat":{"mac":"MACAdr","fw":2.82,"bt":{"t":18.3,"v":19.35,"p":100,"nr":14,"c":0,"m":0},"dmp":[-1.1,-2.2,214.2],"st":{"b":653,"d":9170,"wt":689,"bl":47},"ls":31,"le":0,"lz":0,"rsi":-71,"lk":1,"act":1,"conn":"wifi"}}
2019-06-11 20:27:50.226 - debug: worx.0 Test Status: 31
2019-06-11 20:28:00.229 - debug: worx.0 Edcut send cmd:2
2019-06-11 20:28:14.039 - debug: worx.0 DATA: {"cfg":{"id":0,"lg":"it","tm":"20:28:12","dt":"11/06/2019","sc":{"m":1,"p":0,"d":[["00:00",0,0],["00:00",0,1],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,1],["00:00",0,0]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"SerialNr"},"dat":{"mac":"MACAdr","fw":2.82,"bt":{"t":18.3,"v":19.3,"p":100,"nr":14,"c":0,"m":0},"dmp":[-4.2,-4.3,286.9],"st":{"b":653,"d":9170,"wt":689,"bl":47},"ls":31,"le":0,"lz":0,"rsi":-71,"lk":1,"act":1,"conn":"wifi"}}
2019-06-11 20:28:14.040 - debug: worx.0 Test Status: 31
2019-06-11 20:28:24.051 - debug: worx.0 Edcut send cmd:2
2019-06-11 20:28:25.623 - debug: worx.0 DATA: {"cfg":{"id":0,"lg":"it","tm":"20:28:23","dt":"11/06/2019","sc":{"m":1,"p":0,"d":[["00:00",0,0],["00:00",0,1],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,1],["00:00",0,0]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"SerialNr"},"dat":{"mac":"MACAdr","fw":2.82,"bt":{"t":18.3,"v":19.28,"p":100,"nr":14,"c":0,"m":0},"dmp":[-8.2,3,189.3],"st":{"b":653,"d":9170,"wt":689,"bl":47},"ls":34,"le":0,"lz":0,"rsi":-71,"lk":1,"act":1,"conn":"wifi"}}
2019-06-11 20:28:25.625 - debug: worx.0 Test Status: 34
2019-06-11 20:28:25.631 - debug: worx.0 Edcut send cmd:3
2019-06-11 20:28:27.372 - debug: worx.0 DATA: {"cfg":{"id":1,"lg":"it","tm":"20:28:25","dt":"11/06/2019","sc":{"m":1,"p":0,"d":[["00:00",0,0],["00:00",0,1],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,1],["00:00",0,0]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"SerialNr"},"dat":{"mac":"MACAdr","fw":2.82,"bt":{"t":18.2,"v":19.37,"p":100,"nr":14,"c":0,"m":0},"dmp":[-7.1,2.1,191],"st":{"b":653,"d":9170,"wt":689,"bl":47},"ls":5,"le":0,"lz":0,"rsi":-71,"lk":1,"act":1,"conn":"wifi"}}
2019-06-11 20:28:27.375 - debug: worx.0 Test Status: 5
2019-06-11 20:28:30.849 - debug: worx.0 DATA: {"cfg":{"id":0,"lg":"it","tm":"20:28:29","dt":"11/06/2019","sc":{"m":1,"p":0,"d":[["00:00",0,0],["00:00",0,1],["00:00",0,0],["00:00",0,0],["00:00",0,0],["00:00",0,1],["00:00",0,0]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"SerialNr"},"dat":{"mac":"MACAdr","fw":2.82,"bt":{"t":18.4,"v":19.18,"p":100,"nr":14,"c":0,"m":0},"dmp":[-7.1,2.1,191],"st":{"b":653,"d":9170,"wt":689,"bl":47},"ls":30,"le":0,"lz":0,"rsi":-71,"lk":1,"act":1,"conn":"wifi"}}
2019-06-11 20:28:30.851 - debug: worx.0 Test Status: 30`

**Comment by MeisterTR** [comment]
Laut dem log hat alles geklappt und er müsste die Kante gemäht haben.  Hierfür werden mehrere Kommandos gesendet und auf deren Umsetzung gewartet: 
Starte Mäher mit ZoneTraining  -->Anhalten( Pause ) mit Verzögerung --> Starte Heimhfahrt (Messer sollten drehen)

In meinem Fall steht die LS unter einem Hochbeet und es ist sehr Verwinkelt wird das Zonetraining in einer Verwinkelten Stelle angehalten kann es zu Fehlern kommen, deswegen der Delay, Der Mäher benötigt aber auch noch einige Sekunden von Empfang der Nachricht bis zum Starten. 

Aber wie schon gesagt Laut denem Log hat alles Geklappt

**Comment by StrayDog2205** [comment]
Okay, dann werde ich mal weiter Probieren die optimale Zeit für meinen zu finden.

Bringt ja natürlich nicht viel, wenn es die westen Meter wegen ein paar kleinen Kurven auslässt/lassen muss.

**Comment by StrayDog2205** [comment]
Okay, dann werde ich mal weiter Probieren die optimale Zeit für meinen zu finden.

Bringt ja natürlich nicht viel, wenn es die ersten Meter wegen ein paar kleinen Kurven auslässt/lassen muss.

**Comment by StrayDog2205** [comment]
Okay, kurzes feedback.

Grundsätzlich funktioniert die Rand-schneide-funktion.

Nur ist bei mir der Startbereich zu verwinkelt, was dann immer wieder zum abbruch/verzögerung geführt hat.

Meine Lösung dafür unter der Version 0.3.1 ist das ivh die Funktiin nicht zum soll-Zeitpunkt starte, sondern kurz vorher den Zeitplan mit der Aufgabe befülle.
Wenn er dann Fertig ist, wird der Zeitplan wieder gelöscht und der Mäher ist wieder Dumm.

Leicht umständlicher, aber funktioniert gut.


Danke! :-)
